server_names = ['ea-dns.rubyfish.cn', 'uw-dns.rubyfish.cn']
listen_addresses = ['127.0.0.1:65053']
tls_cipher_suite = [52392, 49199]
block_ipv6 = true
#force_tcp = true

[static]
[static.'ea-dns.rubyfish.cn']
stamp = 'sdns://AgUAAAAAAAAAAAASZWEtZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk'

[static.'uw-dns.rubyfish.cn']
stamp = 'sdns://AgUAAAAAAAAAAAASdXctZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk'

server_names = ['my-server']
[static.'my-server']
stamp = 'sdns://AQcAAAAAAAAAFDE1Mi4zMi4xMzQuMTk4OjIyMzM3IJLXKr0fbOTaM3IwscohjLcPw-VHPNVTVtYV6x7RfEGaIDIuZG5zY3J5cHQtY2VydC5leGFtcGxlXzIub25saW5l'
